
services:
  jellyfin-sm:
    image: ghcr.io/gd-benzz/spacemaster-jellyfin:latest


    container_name: jellyfin-sm
    restart: unless-stopped
    ports:
      - "8096:8096"
    volumes:
      - ./config:/config
      - ./cache:/cache
      - /opt/spacemaster:/opt/spacemaster
    environment:
      - SM_DOWNMIX=1

